package com.gy.model.mapper;

import com.gy.model.pojo.TbOrderOperator;
import com.gy.model.pojo.TbOrderOperatorExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TbOrderOperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_operator
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    int countByExample(TbOrderOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_operator
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    int deleteByExample(TbOrderOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_operator
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    @Delete({
        "delete from tb_order_operator",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_operator
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    @Insert({
        "insert into tb_order_operator (id, order_table_name, ",
        "order_id, seller_id, ",
        "user_id, order_state, ",
        "opt_type, opt_content, ",
        "opt_sql, opt_time, ",
        "create_time)",
        "values (#{id,jdbcType=INTEGER}, #{orderTableName,jdbcType=VARCHAR}, ",
        "#{orderId,jdbcType=VARCHAR}, #{sellerId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{orderState,jdbcType=INTEGER}, ",
        "#{optType,jdbcType=VARCHAR}, #{optContent,jdbcType=VARCHAR}, ",
        "#{optSql,jdbcType=VARCHAR}, #{optTime,jdbcType=TIMESTAMP,typeHandler=com.tuan800.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{createTime,jdbcType=TIMESTAMP,typeHandler=com.tuan800.mybatis.typehandler.JodaDateTime2TimestampTypeHandler})"
    })
    int insert(TbOrderOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_operator
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    int insertSelective(TbOrderOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_operator
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    List<TbOrderOperator> selectByExample(TbOrderOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_operator
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    @Select({
        "select",
        "id, order_table_name, order_id, seller_id, user_id, order_state, opt_type, opt_content, ",
        "opt_sql, opt_time, create_time",
        "from tb_order_operator",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TbOrderOperator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_operator
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") TbOrderOperator record, @Param("example") TbOrderOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_operator
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    int updateByExample(@Param("record") TbOrderOperator record, @Param("example") TbOrderOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_operator
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    int updateByPrimaryKeySelective(TbOrderOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_operator
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    @Update({
        "update tb_order_operator",
        "set order_table_name = #{orderTableName,jdbcType=VARCHAR},",
          "order_id = #{orderId,jdbcType=VARCHAR},",
          "seller_id = #{sellerId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "order_state = #{orderState,jdbcType=INTEGER},",
          "opt_type = #{optType,jdbcType=VARCHAR},",
          "opt_content = #{optContent,jdbcType=VARCHAR},",
          "opt_sql = #{optSql,jdbcType=VARCHAR},",
          "opt_time = #{optTime,jdbcType=TIMESTAMP,typeHandler=com.tuan800.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "create_time = #{createTime,jdbcType=TIMESTAMP,typeHandler=com.tuan800.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TbOrderOperator record);
}