package com.gy.model.pojo;

import org.joda.time.DateTime;

public class TbOrderOperator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_operator.id
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_operator.order_table_name
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    private String orderTableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_operator.order_id
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_operator.seller_id
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    private Integer sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_operator.user_id
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_operator.order_state
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    private Integer orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_operator.opt_type
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    private String optType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_operator.opt_content
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    private String optContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_operator.opt_sql
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    private String optSql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_operator.opt_time
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    private DateTime optTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_operator.create_time
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    private DateTime createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_operator.id
     *
     * @return the value of tb_order_operator.id
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_operator.id
     *
     * @param id the value for tb_order_operator.id
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_operator.order_table_name
     *
     * @return the value of tb_order_operator.order_table_name
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public String getOrderTableName() {
        return orderTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_operator.order_table_name
     *
     * @param orderTableName the value for tb_order_operator.order_table_name
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public void setOrderTableName(String orderTableName) {
        this.orderTableName = orderTableName == null ? null : orderTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_operator.order_id
     *
     * @return the value of tb_order_operator.order_id
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_operator.order_id
     *
     * @param orderId the value for tb_order_operator.order_id
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_operator.seller_id
     *
     * @return the value of tb_order_operator.seller_id
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public Integer getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_operator.seller_id
     *
     * @param sellerId the value for tb_order_operator.seller_id
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public void setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_operator.user_id
     *
     * @return the value of tb_order_operator.user_id
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_operator.user_id
     *
     * @param userId the value for tb_order_operator.user_id
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_operator.order_state
     *
     * @return the value of tb_order_operator.order_state
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_operator.order_state
     *
     * @param orderState the value for tb_order_operator.order_state
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_operator.opt_type
     *
     * @return the value of tb_order_operator.opt_type
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public String getOptType() {
        return optType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_operator.opt_type
     *
     * @param optType the value for tb_order_operator.opt_type
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public void setOptType(String optType) {
        this.optType = optType == null ? null : optType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_operator.opt_content
     *
     * @return the value of tb_order_operator.opt_content
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public String getOptContent() {
        return optContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_operator.opt_content
     *
     * @param optContent the value for tb_order_operator.opt_content
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public void setOptContent(String optContent) {
        this.optContent = optContent == null ? null : optContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_operator.opt_sql
     *
     * @return the value of tb_order_operator.opt_sql
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public String getOptSql() {
        return optSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_operator.opt_sql
     *
     * @param optSql the value for tb_order_operator.opt_sql
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public void setOptSql(String optSql) {
        this.optSql = optSql == null ? null : optSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_operator.opt_time
     *
     * @return the value of tb_order_operator.opt_time
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public DateTime getOptTime() {
        return optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_operator.opt_time
     *
     * @param optTime the value for tb_order_operator.opt_time
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public void setOptTime(DateTime optTime) {
        this.optTime = optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_operator.create_time
     *
     * @return the value of tb_order_operator.create_time
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public DateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_operator.create_time
     *
     * @param createTime the value for tb_order_operator.create_time
     *
     * @mbggenerated Wed Dec 14 14:45:31 CST 2016
     */
    public void setCreateTime(DateTime createTime) {
        this.createTime = createTime;
    }
}